### ISSUE TITLE
remove my email id from your file

### ISSUE THREAD

**Issue by aminurr** [aminurislamarnob/crud-html-template#1]
https://github.com/aminurislamarnob/crud-html-template/blob/master/index.html you are using my email in this file at line 59. I am reporting that to git hub and also requesting you to delete my email id reference from your code.

**Comment by aminurislamarnob** [comment]
Sorry, it was used unintionally. I am removing it ASAP

**Comment by aminurislamarnob** [comment]
I have removed your email address. Again, Sorry about that
